version: '3.7'
services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8080
    environment:
      - SECRET_KEY=mil6-@nsz47(hpv)q_ws4!b4z5digj+orgp9yxhe$$vvp8_ighd
      - DEBUG=1
    volumes:
      - .:/code
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
volumes:
  postgres_data:
